const translations = {
    ru: {
        title: "Sweet Home",
        "nav-services": "Услуги",
        "nav-advantages": "Преимущества",
        "nav-about": "О нас",
        "nav-contact": "Контакты",
        "hero-title": "Найти дом своей мечты",
        "hero-text": "Мы поможем вам подобрать идеальное жилье для вашего комфорта.",
        "form-title": "Оставьте заявку",
        "input-name": "Ваше имя",
        "input-phone": "Ваш телефон",
        "input-type": "Тип заявки",
        "option-default": "Тип заявки",
        "btn-submit": "Отправить",  // <-- Здесь добавлена запятая
        "about_us": "О нас",
        "about_text": "Sweet Home - это агентство недвижимости с многолетним опытом и глубокими знаниями рынка недвижимости. Мы предлагаем профессиональную помощь на каждом этапе — от подбора идеального жилья до заключения сделки. Наша команда состоит из квалифицированных специалистов, которые заботятся о каждом клиенте и делают всё возможное, чтобы ваше сотрудничество с нами было комфортным, прозрачным и успешным. Мы понимаем, насколько важен вопрос жилья, и стремимся найти лучшие решения, которые будут соответствовать вашим потребностям и бюджету. Доверие клиентов — наш главный приоритет, поэтому мы гарантируем безопасность, юридическую чистоту и оперативность всех операций.",
        "numbers_title": "Мы в цифрах",
        "years_success": "лет успешной работы",
        "objects_in_base": "объектов в базе",
        "avg_sale_time": "месяца – средний срок продажи",
        "happy_clients": "довольных клиентов",
        "services_title": "Наши Услуги",
        "service_buy": "Покупка",
        "service_buy_text": "Подбор недвижимости по вашим критериям и помощь в заключении сделки.",
        "service_sell": "Продажа",
        "service_sell_text": "Организация продажи с максимальной выгодой для вас.",
        "more_details": "Подробнее",
        "service_commercial": "Коммерческая недвижимость",
        "service_commercial_text": "Подбор, продажа и аренда коммерческих объектов для бизнеса.",
        "service_rent": "Аренда",
        "service_rent_text": "Надежные варианты аренды для комфортного проживания.",
        "service_international": "Международная недвижимость",
        "service_international_text": "Помогаем приобрести недвижимость за границей: Турция, Кипр, Болгария, Дубай, Таиланд.",
        "service_legalization": "Узаконивание перепланировок и ввод в эксплуатацию",
        "service_legalization_text": "Помогаем узаконить любые перепланировки и ввести объект в эксплуатацию.",
        "partners_title": "Наши партнеры",
        "advantages_title": "Наши преимущества",
        "advantage_contract": "Онлайн-договор",
        "advantage_contract_text": "Заключение сделки без необходимости личной встречи.",
        "advantage_advertising": "Активная реклама",
        "advantage_advertising_text": "Продвижение вашей недвижимости на популярных платформах.",
        "advantage_fast_sale": "Быстрая продажа",
        "advantage_fast_sale_text": "Средний срок продажи – от 1 до 2 месяцев.",
        "reviews_title": "Отзывы наших клиентов",
        "review_1_name": "Динара Капизова",
        "review_1_date": "12 марта 2025",
        "review_1_text": "Хочу поблагодарить Наталью за помощь в продаже квартиры в короткие сроки. Наталья - профессионал с большой буквы. Удачи и процветания вашей команде профессионалов!",
        "review_2_name": "Nizam Sadyrov",
        "review_2_date": "5 февраля 2025",
        "review_2_text": "Огромная благодарность Гусельниковой Юлии! Спасибо за внимательное отношение и помощь в поиске съёмного жилья!",
        "review_3_name": "Константин Банченко",
        "review_3_date": "20 января 2025",
        "review_3_text": "Огромное спасибо Юле! Профессионал своего дела. От первого звонка до полного сопровождения сделки. Остались очень довольны!",
        "review_4_name": "Гульназ Салимова",
        "review_4_date": "28 марта 2025",
        "review_4_text": "Спасибо Sweet Home за профессионализм. Нашли идеальную квартиру по отличной цене. Поняли наши пожелания с первого раза.",
        "review_5_name": "Ольга Мендыбаева",
        "review_5_date": "8 апреля 2025",
        "review_5_text": "Благодарю компанию Sweet Home и риэлтора Наталью! Всё оперативно, быстро и с вниманием к деталям. Сделали скидку, спасибо!",
        "review_6_name": "Рустам Ахметов",
        "review_6_date": "15 февраля 2025",
        "review_6_text": "Отличная работа Sweet Home! Процесс покупки квартиры прошел без нервов. Риэлторы всегда были на связи, спасибо!",
        "banner_title": "ИМЕЕМ СТАТУС 'КРЫША АГЕНТ'",
        "banner_text": "Все наши объекты всегда на первых местах на портале KRISHA.KZ!",
        "banner_button": "СВЯЗАТЬСЯ",
        "contact_title": "Наши контакты",
        "contact_address": "📍 Казахстан, г. Алматы, Проспект Абая, 76/109",
        "contact_phone_1": "📞 +7 (727) 222 35 45",
        "contact_phone_2": "📞 +7 (707) 832 88 07",
        "contact_phone_3": "📞 +7 (701) 765 76 53",
        "contact_email": "Sweethome.kz@mail.ru",
        "contact_form_title": "Оставьте заявку",
        "form_name_placeholder": "Ваше имя",
        "form_phone_placeholder": "Ваш телефон",
        "form_select_option": "Тип заявки",
        "form_option_buy": "Покупка",
        "form_option_sell": "Продажа",
        "form_option_rent": "Аренда",
        "form_submit": "Отправить",
        "footer_contact": "Свяжитесь с нами...",
        "footer_copyright": "© 2024 Sweet Home | Агентство недвижимости",
        "footer_privacy": "Политика конфиденциальности"
    },
    en: {
        title: "Sweet Home",
        "nav-services": "Services",
        "nav-advantages": "Advantages",
        "nav-about": "About Us",
        "nav-contact": "Contacts",
        "hero-title": "Find Your Dream Home",
        "hero-text": "We will help you find the perfect home for your comfort.",
        "form-title": "Leave a Request",
        "input-name": "Your name",
        "input-phone": "Your phone",
        "input-type": "Request type",
        "option-default": "Request type",
        "option-buy": "Buy",
        "option-sell": "Sell",
        "option-rent": "Rent",
        "btn-submit": "Send",
        "about_us": "About Us",
        "about_text": "Sweet Home is a real estate agency with many years of experience and deep knowledge of the real estate market. We offer professional assistance at every stage - from choosing the perfect home to concluding a deal. Our team consists of qualified specialists who care about each client and do everything possible to ensure that your cooperation with us is comfortable, transparent and successful. We understand how important the housing issue is, and we strive to find the best solutions that will meet your needs and budget. Client trust is our top priority, so we guarantee safety, legal purity and efficiency of all transactions.",
        "numbers_title": "Our Numbers",
        "years_success": "years of successful work",
        "objects_in_base": "properties in database",
        "avg_sale_time": "months – average selling time",
        "happy_clients": "satisfied clients",
        "services_title": "Our Services",
        "service_buy": "Buying",
        "service_buy_text": "Property selection based on your criteria and assistance in closing the deal.",
        "service_sell": "Selling",
        "service_sell_text": "Selling organization with maximum benefit for you.",
        "more_details": "Learn More",
        "service_commercial": "Commercial Real Estate",
        "service_commercial_text": "Selection, sale, and rental of commercial properties for business.",
        "service_rent": "Rent",
        "service_rent_text": "Reliable rental options for comfortable living.",
        "service_international": "International Real Estate",
        "service_international_text": "We help you purchase property abroad: Turkey, Cyprus, Bulgaria, Dubai, Thailand.",
        "service_legalization": "Legalization of redesigns and commissioning",
        "service_legalization_text": "We help legalize any redesigns and put the property into operation.",
        "partners_title": "Our Partners",
        "advantages_title": "Our Advantages",
        "advantage_contract": "Online Contract",
        "advantage_contract_text": "Closing the deal without the need for a personal meeting.",
        "advantage_advertising": "Active Advertising",
        "advantage_advertising_text": "Promotion of your property on popular platforms.",
        "advantage_fast_sale": "Fast Sale",
        "advantage_fast_sale_text": "Average sale time – from 1 to 2 months.",
        "reviews_title": "Client Reviews",
        "review_1_name": "Dinaara Kapizova",
        "review_1_date": "March 12, 2025",
        "review_1_text": "I would like to thank Natalia for her help in selling the apartment in a short period. Natalia is a true professional. Wishing success and prosperity to your team of professionals!",
        "review_2_name": "Nizam Sadyrov",
        "review_2_date": "February 5, 2025",
        "review_2_text": "Huge thanks to Yulia Guselnikova! Thank you for your attentive approach and help in finding rental housing!",
        "review_3_name": "Konstantin Banchinko",
        "review_3_date": "January 20, 2025",
        "review_3_text": "A big thank you to Yulia! A professional in her field. From the first call to complete deal support. We are very pleased!",
        "review_4_name": "Gulnaz Salimova",
        "review_4_date": "March 28, 2025",
        "review_4_text": "Thank you Sweet Home for your professionalism. We found the perfect apartment at a great price. You understood our wishes right away.",
        "review_5_name": "Olga Mendybaeva",
        "review_5_date": "April 8, 2025",
        "review_5_text": "Thank you Sweet Home and realtor Natalia! Everything was fast, efficient, and with attention to detail. They gave a discount, thank you!",
        "review_6_name": "Rustam Akhmetov",
        "review_6_date": "February 15, 2025",
        "review_6_text": "Great work by Sweet Home! The process of buying an apartment was smooth. Realtors were always in touch, thank you!",
        "banner_title": "WE HAVE THE STATUS 'KRISHA AGENT'",
        "banner_text": "All our properties are always at the top on the KRISHA.KZ portal!",
        "banner_button": "CONTACT US",
        "contact_title": "Our Contacts",
        "contact_address": "📍 Kazakhstan, Almaty, Abai Avenue, 76/109",
        "contact_phone_1": "📞 +7 (727) 222 35 45",
        "contact_phone_2": "📞 +7 (707) 832 88 07",
        "contact_phone_3": "📞 +7 (701) 765 76 53",
        "contact_email": "Sweethome.kz@mail.ru",
        "contact_form_title": "Leave a Request",
        "form_name_placeholder": "Your Name",
        "form_phone_placeholder": "Your Phone",
        "form_select_option": "Request Type",
        "form_option_buy": "Purchase",
        "form_option_sell": "Sale",
        "form_option_rent": "Rent",
        "form_submit": "Submit",
        "footer_contact": "Contact Us...",
        "footer_copyright": "© 2024 Sweet Home | Real Estate Agency",
        "footer_privacy": "Privacy Policy",
    },
    kz: {
        title: "Sweet Home",
        "nav-services": "Қызметтер",
        "nav-advantages": "Артықшылықтар",
        "nav-about": "Біз туралы",
        "about_us": "Біз туралы",
        "nav-contact": "Байланыс",
        "hero-title": "Армандаған үйіңізді табыңыз",
        "hero-text": "Сізге ыңғайлы үй табуға көмектесеміз.",
        "form-title": "Өтінім қалдырыңыз",
        "input-name": "Сіздің атыңыз",
        "input-phone": "Сіздің телефон",
        "input-type": "Өтінім түрі",
        "option-default": "Өтінім түрі",
        "service_buy": "Сатып алу",
        "service_sell": "Сату",
        "service_rent": "Жалға алу",
        "btn-submit": "Жіберу",
        "about_text": "Sweet Home – көп жылдық тәжірибесі бар және жылжымайтын мүлік нарығын терең білетін жылжымайтын мүлік агенттігі. Біз әр кезеңде кәсіби көмек ұсынамыз - тамаша үйді таңдаудан бастап мәмілені жасауға дейін. Біздің команда әр клиентке қамқорлық жасайтын және бізбен ынтымақтастығыңыз ыңғайлы, ашық және табысты болуы үшін қолдан келгеннің бәрін жасайтын білікті мамандардан тұрады. Біз тұрғын үйдің қаншалықты маңызды екенін түсінеміз және сіздің қажеттіліктеріңіз бен бюджетіңізге сәйкес келетін ең жақсы шешімдерді табуға тырысамыз. Клиенттердің сенімі біздің басты басымдылығымыз болып табылады, сондықтан біз барлық транзакциялардың қауіпсіздігіне, заңды тазалығына және тиімділігіне кепілдік береміз.",
        "numbers_title": "Біз сандарда",
        "years_success": "жыл табысты жұмыс",
        "objects_in_base": "базадағы нысандар",
        "avg_sale_time": "ай – орташа сату уақыты",
        "happy_clients": "қанағаттанған клиенттер",
        "services_title": "Біздің Қызметтер",
        "service_buy_text": "Сіз үшін мінсіз жылжымайтын мүлікті таңдау және мәмілені аяқтауға көмек.",
        "service_sell_text": "Сіздің пайдаңызға барынша тиімді сату ұйымдастыру.",
        "more_details": "Толығырақ",
        "service_commercial": "Коммерциялық жылжымайтын мүлік",
        "service_commercial_text": "Бизнес үшін коммерциялық объектілерді таңдау, сату және жалға алу.",
        "service_rent": "Жалға алу",
        "service_rent_text": "Қолайлы тұрмыс үшін сенімді жалға алу нұсқалары.",
        "service_international": "Халықаралық жылжымайтын мүлік",
        "service_international_text": "Біз шетелден жылжымайтын мүлік сатып алуға көмектесеміз: Түркия, Кипр, Болгария, Дубай, Тайланд.",
        "service_legalization": "Қайта жоспарлау мен пайдалануға беру заңдастыру",
        "service_legalization_text": "Біз кез келген қайта жоспарлауды заңдастыруға және объектіні пайдалануға беруге көмектесеміз.",
        "partners_title": "Біздің серіктестер",
        "advantages_title": "Біздің артықшылықтарымыз",
        "advantage_contract": "Онлайн келісімшарт",
        "advantage_contract_text": "Кездесу жасамай мәміле жасасу.",
        "advantage_advertising": "Белсенді жарнама",
        "advantage_advertising_text": "Сіздің мүлігіңізді танымал платформаларда жарнамалау.",
        "advantage_fast_sale": "Жылдам сату",
        "advantage_fast_sale_text": "Орташа сату уақыты – 1-2 ай.",
        "reviews_title": "Клиенттердің пікірлері",
        "review_1_name": "Динара Капизова",
        "review_1_date": "2025 жылдың 12 наурызы",
        "review_1_text": "Қысқа мерзімде пәтерді сатуда көмектескені үшін Натальяға рахмет айтамын. Наталья – үлкен әріппен жазылатын кәсіби маман. Сіздердің кәсіби командаңызға сәттілік пен гүлдену тілеймін!",
        "review_2_name": "Nizam Sadyrov",
        "review_2_date": "2025 жылдың 5 ақпаны",
        "review_2_text": "Юлия Гусельниковаға үлкен рахмет! Жеке тұрғын үйді іздеуде көрсеткен жанашырлығы мен көмегі үшін алғыс айтамын!",
        "review_3_name": "Константин Банченко",
        "review_3_date": "2025 жылдың 20 қаңтары",
        "review_3_text": "Юлияға үлкен рахмет! Өз ісінің кәсіби маманы. Алғашқы қоңыраудан бастап мәмілені толық супроводка жасағанға дейін. Біз өте қуаныштымыз!",
        "review_4_name": "Гульназ Салимова",
        "review_4_date": "2025 жылдың 28 наурызы",
        "review_4_text": "Sweet Home-ға кәсібилігі үшін рахмет. Біз тамаша пәтерді керемет бағамен таптық. Олар біздің тілектерімізді бірінші ретте-ақ түсінді.",
        "review_5_name": "Ольга Мендыбаева",
        "review_5_date": "2025 жылдың 8 сәуірі",
        "review_5_text": "Sweet Home компаниясына және риэлтор Натальяға рахмет! Барлығы жедел, жылдам және егжей-тегжейге назар аударылып жасалды. Жеңілдік жасады, рахмет!",
        "review_6_name": "Рустам Ахметов",
        "review_6_date": "2025 жылдың 15 ақпаны",
        "review_6_text": "Sweet Home-ға керемет жұмыс! Пәтер сатып алу процесі жүйелі өтті. Риэлторлар әрқашан байланыста болды, рахмет!",
        "banner_title": "БІЗДЕ 'KRISHA AGENT' СТАТУСЫ БАР",
        "banner_text": "Барлық біздің объектілеріміз әрқашан KRISHA.KZ порталында ең жоғарғы орындарда!",
        "banner_button": "БІЗБЕН БАЙЛАНЫСЫҢЫЗ",
        "contact_title": "Біздің байланыстар",
        "contact_address": "📍 Қазақстан, Алматы қаласы, Абая даңғылы, 76/109",
        "contact_phone_1": "📞 +7 (727) 222 35 45",
        "contact_phone_2": "📞 +7 (707) 832 88 07",
        "contact_phone_3": "📞 +7 (701) 765 76 53",
        "contact_email": "Sweethome.kz@mail.ru",
        "contact_form_title": "Өтініш қалдыру",
        "form_name_placeholder": "Атыңыз",
        "form_phone_placeholder": "Телефоныңыз",
        "form_select_option": "Өтініш түрі",
        "form_option_buy": "Сатып алу",
        "form_option_sell": "Сату",
        "form_option_rent": "Жалға алу",
        "form_submit": "Жіберу",
        "footer_contact": "Бізбен байланысыңыз...",
        "footer_copyright": "© 2024 Sweet Home | Жылжымайтын мүлік агенттігі",
        "footer_privacy": "Құпиялылық саясаты",
    }
};


// Функция смены языка
function changeLanguage(lang) {
    document.querySelectorAll("[data-key]").forEach(element => {
        let key = element.getAttribute("data-key");
        if (translations[lang][key]) {
            if (element.tagName === "INPUT" || element.tagName === "SELECT") {
                element.placeholder = translations[lang][key]; // Для input/placeholder
            } else if (element.tagName === "OPTION") {
                element.textContent = translations[lang][key]; // Для option
            } else {
                element.textContent = translations[lang][key]; // Для других элементов
            }
        }
    });

    // Сохранение выбора языка в LocalStorage
    localStorage.setItem("selectedLanguage", lang);
}

// Обработчик смены языка
document.getElementById("language-switcher").addEventListener("change", function () {
    changeLanguage(this.value);
});

// Установка сохраненного языка при загрузке страницы
document.addEventListener("DOMContentLoaded", function () {
    let savedLang = localStorage.getItem("selectedLanguage") || "ru";
    document.getElementById("language-switcher").value = savedLang;
    changeLanguage(savedLang);
});
